[pytest]
addopts = -v --tb=short --html=report.html --self-contained-html --alluredir=allure-results
testpaths = tests/step_defs
bdd_features_base_dir = tests/features
filterwarnings =
    ignore::DeprecationWarning
markers =
    login: Testes relacionados ao fluxo de autenticacao
    cart: Testes relacionados ao carrinho de compras
    checkout: Testes do fluxo de finalizacao de compra
    happy_path: Cenarios de caminho feliz (sucesso)
    edge_case: Cenarios de erro, validacoes e limites
    e2e: Testes de ponta a ponta (End-to-End)